version: "3"

services:
#  chatter:
#    depends_on:
#      - db
#    build:
#      context: .
#    image: chatter:0.0.0
#    restart: on-failure
#    ports:
#      - 80:80

  db:
    image: mariadb:11.4.2
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: chatter
    ports:
      - 3306:3306
