version: "3"

networks:
  default:
    name: docker-network

services:
  chatter:
    depends_on:
      - db
    build:
      context: .
    image: chatter:0.0.0
    networks:
      - default
    restart: on-failure
    ports:
      - 80:80

  db:
    image: mariadb:11.4.2
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: chatter
